# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""
initial schema.

Revision ID: e373726d391b
Revises:
Create Date: 2026-04-23 11:32:09.031850
"""

import uuid
from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.sqlite import CHAR
from sqlalchemy.engine import Dialect
from sqlalchemy.types import TypeDecorator, Uuid


class _CustomUUID(TypeDecorator[uuid.UUID]):
    """
    Frozen copy of CustomUUID kept here so this revision stays self-contained.

    This class is embedded in the migration script rather than imported to ensure
    the migration remains reproducible and independent of future changes to the
    main CustomUUID implementation in memory_models.py. Any future modifications
    to CustomUUID must NOT affect this frozen version.
    """

    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect: Dialect) -> Any:
        if dialect.name == "sqlite":
            return dialect.type_descriptor(CHAR(36))
        return dialect.type_descriptor(Uuid())

    def process_bind_param(self, value: Any, dialect: Any) -> str | None:
        return str(value) if value is not None else None

    def process_result_value(self, value: Any, dialect: Any) -> uuid.UUID | None:
        if value is None:
            return None
        if isinstance(value, uuid.UUID):
            return value
        return uuid.UUID(value)


# revision identifiers, used by Alembic.
revision: str = "e373726d391b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this schema upgrade."""
    # ### commands auto generated by Alembic and reviewed by author###
    op.create_table(
        "PromptMemoryEntries",
        sa.Column("id", _CustomUUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("sequence", sa.INTEGER(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("prompt_metadata", sa.JSON(), nullable=False),
        sa.Column("targeted_harm_categories", sa.JSON(), nullable=True),
        sa.Column("converter_identifiers", sa.JSON(), nullable=True),
        sa.Column("prompt_target_identifier", sa.JSON(), nullable=False),
        sa.Column("attack_identifier", sa.JSON(), nullable=False),
        sa.Column("response_error", sa.String(), nullable=True),
        sa.Column("original_value_data_type", sa.String(), nullable=False),
        sa.Column("original_value", sa.Unicode(), nullable=False),
        sa.Column("original_value_sha256", sa.String(), nullable=True),
        sa.Column("converted_value_data_type", sa.String(), nullable=False),
        sa.Column("converted_value", sa.Unicode(), nullable=True),
        sa.Column("converted_value_sha256", sa.String(), nullable=True),
        sa.Column("original_prompt_id", _CustomUUID(), nullable=False),
        sa.Column("pyrit_version", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ScenarioResultEntries",
        sa.Column("id", _CustomUUID(), nullable=False),
        sa.Column("scenario_name", sa.String(), nullable=False),
        sa.Column("scenario_description", sa.Unicode(), nullable=True),
        sa.Column("scenario_version", sa.INTEGER(), nullable=False),
        sa.Column("pyrit_version", sa.String(), nullable=False),
        sa.Column("scenario_init_data", sa.JSON(), nullable=True),
        sa.Column("objective_target_identifier", sa.JSON(), nullable=False),
        sa.Column("objective_scorer_identifier", sa.JSON(), nullable=True),
        sa.Column("scenario_run_state", sa.String(), nullable=False),
        sa.Column("attack_results_json", sa.Unicode(), nullable=False),
        sa.Column("display_group_map_json", sa.Unicode(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=True),
        sa.Column("number_tries", sa.INTEGER(), nullable=False),
        sa.Column("completion_time", sa.DateTime(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("error_attack_result_ids_json", sa.Unicode(), nullable=True),
        sa.Column("error_message", sa.Unicode(), nullable=True),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "SeedPromptEntries",
        sa.Column("id", _CustomUUID(), nullable=False),
        sa.Column("value", sa.Unicode(), nullable=False),
        sa.Column("value_sha256", sa.Unicode(), nullable=True),
        sa.Column("data_type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("dataset_name", sa.String(), nullable=True),
        sa.Column("harm_categories", sa.JSON(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("authors", sa.JSON(), nullable=True),
        sa.Column("groups", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("date_added", sa.DateTime(), nullable=False),
        sa.Column("added_by", sa.String(), nullable=False),
        sa.Column("prompt_metadata", sa.JSON(), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("prompt_group_id", _CustomUUID(), nullable=True),
        sa.Column("sequence", sa.INTEGER(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("seed_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "EmbeddingData",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "embedding",
            sa.ARRAY(sa.Float()).with_variant(sa.JSON(), "mssql").with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("embedding_type_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["PromptMemoryEntries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ScoreEntries",
        sa.Column("id", _CustomUUID(), nullable=False),
        sa.Column("score_value", sa.String(), nullable=False),
        sa.Column("score_value_description", sa.String(), nullable=True),
        sa.Column("score_type", sa.String(), nullable=False),
        sa.Column("score_category", sa.JSON(), nullable=True),
        sa.Column("score_rationale", sa.String(), nullable=True),
        sa.Column("score_metadata", sa.JSON(), nullable=False),
        sa.Column("scorer_class_identifier", sa.JSON(), nullable=False),
        sa.Column("prompt_request_response_id", _CustomUUID(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("task", sa.String(), nullable=True),
        sa.Column("objective", sa.String(), nullable=True),
        sa.Column("pyrit_version", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prompt_request_response_id"],
            ["PromptMemoryEntries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "AttackResultEntries",
        sa.Column("id", _CustomUUID(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("objective", sa.Unicode(), nullable=False),
        sa.Column("attack_identifier", sa.JSON(), nullable=False),
        sa.Column("atomic_attack_identifier", sa.JSON(), nullable=True),
        sa.Column("objective_sha256", sa.String(), nullable=True),
        sa.Column("last_response_id", _CustomUUID(), nullable=True),
        sa.Column("last_score_id", _CustomUUID(), nullable=True),
        sa.Column("executed_turns", sa.INTEGER(), nullable=False),
        sa.Column("execution_time_ms", sa.INTEGER(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("outcome_reason", sa.String(), nullable=True),
        sa.Column("attack_metadata", sa.JSON(), nullable=True),
        sa.Column("pruned_conversation_ids", sa.JSON(), nullable=True),
        sa.Column("adversarial_chat_conversation_ids", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("pyrit_version", sa.String(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Unicode(), nullable=True),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("error_traceback", sa.Unicode(), nullable=True),
        sa.Column("retry_events_json", sa.Unicode(), nullable=True),
        sa.Column("total_retries", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_response_id"],
            ["PromptMemoryEntries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_score_id"],
            ["ScoreEntries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this schema upgrade."""
    # ### commands auto generated by Alembic and reviewed by author ###
    op.drop_table("AttackResultEntries")
    op.drop_table("ScoreEntries")
    op.drop_table("EmbeddingData")
    op.drop_table("SeedPromptEntries")
    op.drop_table("ScenarioResultEntries")
    op.drop_table("PromptMemoryEntries")
    # ### end Alembic commands ###
