# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""
add adversarial prompt template to attack identifiers.

Revision ID: fcecd0617e61
Revises: 7a9c1e3f5b2d
Create Date: 2026-09-23 19:31:12.891216
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcecd0617e61"
down_revision: str | None = "7a9c1e3f5b2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this schema upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("AttackIdentifiers", sa.Column("adversarial_prompt_template", sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this schema upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("AttackIdentifiers", "adversarial_prompt_template")
    # ### end Alembic commands ###
