# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

import os
import tempfile
import uuid
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text

from pyrit.memory.alembic.versions import ab8f2c1a9d07_pre_alembic_release_schema
from pyrit.memory.alembic.versions.ab8f2c1a9d07_pre_alembic_release_schema import _CustomUUID
from pyrit.memory.migration import (
    ALEMBIC_OUTPUT_PREFIX,
    _PrefixedTextStream,
    check_schema_migrations,
    generate_schema_migration,
    run_schema_migrations,
)


def test_prefixed_text_stream_prefixes_each_line():
    """_PrefixedTextStream prepends the prefix to the start of each line, across separate writes."""
    import io

    buffer = io.StringIO()
    stream = _PrefixedTextStream(stream=buffer, prefix="[tag] ")

    # Alembic writes the message and the trailing newline as separate calls.
    assert stream.write("first line") == len("first line")
    assert stream.write("\n") == 1
    stream.write("second\nthird\n")

    assert buffer.getvalue() == "[tag] first line\n[tag] second\n[tag] third\n"


def test_prefixed_text_stream_delegates_attributes():
    """_PrefixedTextStream delegates unknown attributes (e.g. encoding) to the wrapped stream."""
    import io

    buffer = io.StringIO()
    stream = _PrefixedTextStream(stream=buffer, prefix="[tag] ")

    assert stream.getvalue() == ""
    stream.flush()  # delegated, should not raise


def test_alembic_env_raises_when_no_connection():
    """Covers env.py line 15: RuntimeError when connection is None."""
    import importlib
    import sys
    from unittest.mock import MagicMock

    # Build a mock alembic context where config.attributes has no "connection"
    mock_config = MagicMock()
    mock_config.attributes = {}  # .get("connection") → None

    mock_context = MagicMock()
    mock_context.config = mock_config

    # Remove cached env module so reload runs module-level code
    env_module_name = "pyrit.memory.alembic.env"
    saved = sys.modules.pop(env_module_name, None)

    # Patch alembic.context to be our mock context
    import alembic

    original_context = getattr(alembic, "context", None)
    alembic.context = mock_context

    try:
        with pytest.raises(RuntimeError, match="No connection found for Alembic migration"):
            importlib.import_module(env_module_name)
    finally:
        # Restore original state
        alembic.context = original_context
        sys.modules.pop(env_module_name, None)
        if saved is not None:
            sys.modules[env_module_name] = saved


def _get_alembic_head_revision(*, config: Config) -> str:
    """Return the current Alembic head revision for the configured script location."""
    head_revision = ScriptDirectory.from_config(config).get_current_head()
    if head_revision is None:
        raise RuntimeError("No Alembic head revision found for memory migrations.")

    return head_revision


def test_custom_uuid_process_bind_param_with_none():
    """Test _CustomUUID.process_bind_param with None value."""
    uuid_type = _CustomUUID()
    result = uuid_type.process_bind_param(None, None)
    assert result is None


def test_custom_uuid_process_bind_param_with_uuid():
    """Test _CustomUUID.process_bind_param with UUID value."""
    uuid_type = _CustomUUID()
    test_uuid = uuid.uuid4()
    result = uuid_type.process_bind_param(test_uuid, None)
    assert result == str(test_uuid)


def test_custom_uuid_process_result_value_with_none():
    """Test _CustomUUID.process_result_value with None value."""
    uuid_type = _CustomUUID()
    result = uuid_type.process_result_value(None, None)
    assert result is None


def test_custom_uuid_process_result_value_with_uuid():
    """Test _CustomUUID.process_result_value with UUID value."""
    uuid_type = _CustomUUID()
    test_uuid = uuid.uuid4()
    result = uuid_type.process_result_value(test_uuid, None)
    assert result == test_uuid


def test_custom_uuid_process_result_value_with_string():
    """Test _CustomUUID.process_result_value with string value."""
    uuid_type = _CustomUUID()
    test_uuid = uuid.uuid4()
    result = uuid_type.process_result_value(str(test_uuid), None)
    assert result == test_uuid


def test_custom_uuid_load_dialect_impl_sqlite():
    """Test _CustomUUID.load_dialect_impl for SQLite dialect."""
    from sqlalchemy.dialects import sqlite

    uuid_type = _CustomUUID()
    dialect = sqlite.dialect()
    result = uuid_type.load_dialect_impl(dialect)
    assert result is not None


def test_custom_uuid_load_dialect_impl_postgresql():
    """Test _CustomUUID.load_dialect_impl for PostgreSQL dialect."""
    from sqlalchemy.dialects import postgresql

    uuid_type = _CustomUUID()
    dialect = postgresql.dialect()
    result = uuid_type.load_dialect_impl(dialect)
    assert result is not None


def test_run_schema_migrations_applies_head_revision():
    """Test that run_schema_migrations applies the current head revision."""
    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "offline-test.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            pyrit_root = Path(__file__).resolve().parent.parent.parent.parent / "pyrit"
            script_location = pyrit_root / "memory" / "alembic"
            config = Config()
            config.set_main_option("script_location", str(script_location))
            expected_head = _get_alembic_head_revision(config=config)

            run_schema_migrations(engine=engine)

            with engine.connect() as connection:
                version = connection.execute(text("SELECT version_num FROM pyrit_memory_alembic_version")).scalar_one()
            assert version == expected_head
        finally:
            engine.dispose()


def test_migration_online_mode():
    """
    Test that online migration configuration is valid.
    This tests the run_migrations_online path in env.py.
    """
    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "online-test.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            with engine.begin() as connection:
                pyrit_root = Path(__file__).resolve().parent.parent.parent.parent / "pyrit"
                script_location = pyrit_root / "memory" / "alembic"
                config = Config()
                config.set_main_option("script_location", str(script_location))
                config.attributes["connection"] = connection
                config.attributes["version_table"] = "pyrit_memory_alembic_version"
                expected_head = _get_alembic_head_revision(config=config)

                command.upgrade(config, "head")

                version = connection.execute(text("SELECT version_num FROM pyrit_memory_alembic_version")).scalar_one()
                assert version == expected_head
        finally:
            engine.dispose()


def test_migration_script_metadata():
    """Test that the initial migration script has correct metadata."""

    assert ab8f2c1a9d07_pre_alembic_release_schema.revision == "ab8f2c1a9d07"
    assert ab8f2c1a9d07_pre_alembic_release_schema.down_revision is None
    assert ab8f2c1a9d07_pre_alembic_release_schema.branch_labels is None
    assert ab8f2c1a9d07_pre_alembic_release_schema.depends_on is None


def test_migration_downgrade_creates_proper_structure():
    """
    Test that downgrade function doesn't corrupt the database.
    This indirectly tests the downgrade path in ab8f2c1a9d07_pre_alembic_release_schema.py.
    """
    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "downgrade-test.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            with engine.begin() as connection:
                pyrit_root = Path(__file__).resolve().parent.parent.parent.parent / "pyrit"
                script_location = pyrit_root / "memory" / "alembic"
                config = Config()
                config.set_main_option("script_location", str(script_location))
                config.attributes["connection"] = connection
                config.attributes["version_table"] = "pyrit_memory_alembic_version"

                command.upgrade(config, "head")

                tables_before = set(inspect(connection).get_table_names())
                assert len(tables_before) > 0

                command.downgrade(config, "base")

                tables_after = set(inspect(connection).get_table_names())
                assert "pyrit_memory_alembic_version" not in tables_after or len(tables_after) == 1
        finally:
            engine.dispose()


# =============================================================================
# Backfill tests for the attribution_parent_id foreign key migration
# =============================================================================


_SCENARIO_LINKAGE_REV = "9c8b7a6d5e4f"
_PREV_REV = "7a1b2c3d4e5f"


def _seed_pre_migration_scenario(connection, *, scenario_id, manifest_json):
    """Insert a ScenarioResultEntry row at the pre-migration revision."""
    connection.execute(
        text(
            'INSERT INTO "ScenarioResultEntries" '
            "(id, scenario_name, scenario_description, scenario_version, pyrit_version, "
            "objective_target_identifier, scenario_run_state, attack_results_json, "
            "number_tries, completion_time, timestamp) "
            "VALUES (:id, :name, '', 1, '0.14.0.dev0', '{}', 'COMPLETED', :manifest, 0, '2026-05-18', '2026-05-18')"
        ),
        {"id": scenario_id, "name": "Backfill Test", "manifest": manifest_json},
    )


def _seed_pre_migration_attack_result(connection, *, attack_id, conversation_id):
    """Insert an AttackResultEntry row at the pre-migration revision."""
    connection.execute(
        text(
            'INSERT INTO "AttackResultEntries" '
            "(id, conversation_id, objective, attack_identifier, objective_sha256, executed_turns, "
            "execution_time_ms, outcome, timestamp) "
            "VALUES (:id, :conv, 'obj', '{}', 'sha', 1, 0, 'success', '2026-05-18')"
        ),
        {"id": attack_id, "conv": conversation_id},
    )


def _seed_post_drop_attack_result(connection, *, attack_id, conversation_id):
    """Insert an AttackResultEntry row at the Conversations pre-migration revision.

    By this revision the deprecated ``AttackResultEntries.attack_identifier`` column
    has already been dropped, so it is omitted from the insert.
    """
    connection.execute(
        text(
            'INSERT INTO "AttackResultEntries" '
            "(id, conversation_id, objective, objective_sha256, executed_turns, "
            "execution_time_ms, outcome, timestamp) "
            "VALUES (:id, :conv, 'obj', 'sha', 1, 0, 'success', '2026-05-18')"
        ),
        {"id": attack_id, "conv": conversation_id},
    )


def _config_for(connection):
    pyrit_root = Path(__file__).resolve().parent.parent.parent.parent / "pyrit"
    script_location = pyrit_root / "memory" / "alembic"
    config = Config()
    config.set_main_option("script_location", str(script_location))
    config.attributes["connection"] = connection
    config.attributes["version_table"] = "pyrit_memory_alembic_version"
    return config


def test_backfill_links_attack_results_via_conversation_id():
    """Upgrading from the pre-foreign-key revision backfills
    attribution_parent_id + attribution_data on AttackResultEntries by
    matching conversation_id."""
    import json

    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "backfill-test.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            sid = str(uuid.uuid4())
            ar1_id = str(uuid.uuid4())
            ar2_id = str(uuid.uuid4())
            ar3_id = str(uuid.uuid4())

            with engine.begin() as connection:
                config = _config_for(connection)
                # Step the schema up to JUST before the linkage migration.
                command.upgrade(config, _PREV_REV)

                _seed_pre_migration_attack_result(connection, attack_id=ar1_id, conversation_id="conv-a-0")
                _seed_pre_migration_attack_result(connection, attack_id=ar2_id, conversation_id="conv-a-1")
                _seed_pre_migration_attack_result(connection, attack_id=ar3_id, conversation_id="conv-b-0")
                _seed_pre_migration_scenario(
                    connection,
                    scenario_id=sid,
                    manifest_json=json.dumps({"a": ["conv-a-0", "conv-a-1"], "b": ["conv-b-0"]}),
                )

                command.upgrade(config, _SCENARIO_LINKAGE_REV)

                rows = connection.execute(
                    text(
                        "SELECT conversation_id, attribution_parent_id, attribution_data "
                        'FROM "AttackResultEntries" ORDER BY conversation_id'
                    )
                ).fetchall()

            results_by_conv = {r[0]: (r[1], r[2]) for r in rows}

            # All three rows now point at the scenario via the new foreign key.
            for conv in ("conv-a-0", "conv-a-1", "conv-b-0"):
                assert results_by_conv[conv][0] == sid, f"{conv} should be backfilled"

            # attribution_data carries parent_collection (the atomic attack name).
            sd_a0 = json.loads(results_by_conv["conv-a-0"][1])
            sd_a1 = json.loads(results_by_conv["conv-a-1"][1])
            sd_b0 = json.loads(results_by_conv["conv-b-0"][1])

            assert sd_a0 == {"parent_collection": "a"}
            assert sd_a1 == {"parent_collection": "a"}
            assert sd_b0 == {"parent_collection": "b"}
        finally:
            engine.dispose()


def test_backfill_is_idempotent_and_does_not_clobber_existing_linkage():
    """The backfill is safe to re-run: rows that already carry an
    ``attribution_parent_id`` are not overwritten (the WHERE IS NULL guard). We
    verify by upgrading, manually retargeting a row, then downgrading +
    re-upgrading and asserting the manual retarget survives."""
    import json

    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "idempotent.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            sid_old = str(uuid.uuid4())
            sid_manual = str(uuid.uuid4())
            ar_id = str(uuid.uuid4())

            with engine.begin() as connection:
                config = _config_for(connection)
                command.upgrade(config, _PREV_REV)
                _seed_pre_migration_attack_result(connection, attack_id=ar_id, conversation_id="conv-shared")
                _seed_pre_migration_scenario(
                    connection, scenario_id=sid_old, manifest_json=json.dumps({"a": ["conv-shared"]})
                )
                command.upgrade(config, _SCENARIO_LINKAGE_REV)

                # Manually retarget the row to a DIFFERENT attribution_parent_id —
                # simulate code that already linked it post-upgrade.
                connection.execute(
                    text('UPDATE "AttackResultEntries" SET attribution_parent_id = :sid WHERE conversation_id = :conv'),
                    {"sid": sid_manual, "conv": "conv-shared"},
                )

                # Downgrade then re-upgrade to re-run the backfill.
                command.downgrade(config, _PREV_REV)

                # After downgrade the foreign key column is gone, but the
                # manifest still references conv-shared. On re-upgrade, the
                # backfill should NOT clobber sid_manual because the column was
                # just re-added as NULL — actually downgrade DROPS the column
                # data, so on re-upgrade the row will start at NULL and get
                # linked again. The test we want is: re-running the backfill
                # while a row already has a non-NULL foreign key does not
                # overwrite it. We exercise that with a fresh second
                # upgrade-then-no-op-re-upgrade.
                command.upgrade(config, _SCENARIO_LINKAGE_REV)

                # First upgrade after downgrade re-links it to sid_old (the
                # manifest source). Now manually retarget again.
                connection.execute(
                    text('UPDATE "AttackResultEntries" SET attribution_parent_id = :sid WHERE conversation_id = :conv'),
                    {"sid": sid_manual, "conv": "conv-shared"},
                )

                # Stamping should NOT happen on re-invocation since the column
                # is already non-NULL. We verify by re-running the backfill
                # logic via downgrade+upgrade is NOT what we want here — we
                # want the IS NULL guard. Simulate by adding another scenario
                # referencing the same conversation_id and re-running the
                # backfill function only.
                connection.execute(
                    text(
                        'INSERT INTO "ScenarioResultEntries" '
                        "(id, scenario_name, scenario_description, scenario_version, pyrit_version, "
                        "objective_target_identifier, scenario_run_state, attack_results_json, "
                        "number_tries, completion_time, timestamp) "
                        "VALUES (:id, 'Other', '', 1, '0.14.0.dev0', '{}', 'COMPLETED', :manifest, 0, "
                        "'2026-05-18', '2026-05-18')"
                    ),
                    {"id": str(uuid.uuid4()), "manifest": json.dumps({"x": ["conv-shared"]})},
                )

                # Manually call the backfill function (loaded via the alembic
                # script directory — modules with leading-digit filenames are
                # not importable through normal Python import).
                from importlib.util import module_from_spec, spec_from_file_location

                migration_path = (
                    Path(__file__).resolve().parent.parent.parent.parent
                    / "pyrit"
                    / "memory"
                    / "alembic"
                    / "versions"
                    / "9c8b7a6d5e4f_add_attribution_to_attack_results.py"
                )
                spec = spec_from_file_location("scenario_linkage_migration", migration_path)
                assert spec is not None and spec.loader is not None
                mig = module_from_spec(spec)
                spec.loader.exec_module(mig)

                from alembic import op as _op_mod

                _original_get_bind = _op_mod.get_bind
                _op_mod.get_bind = lambda: connection
                try:
                    mig._backfill_attribution_linkage()
                finally:
                    _op_mod.get_bind = _original_get_bind

                # The row's manual retarget MUST survive — the IS NULL guard
                # prevents the backfill from overwriting it.
                row = connection.execute(
                    text('SELECT attribution_parent_id FROM "AttackResultEntries" WHERE conversation_id = :conv'),
                    {"conv": "conv-shared"},
                ).scalar_one()
                assert row == sid_manual
        finally:
            engine.dispose()


def test_migration_drops_error_attack_result_ids_json_column():
    """The not-yet-released error_attack_result_ids_json column is removed
    in this migration (no deprecation window needed)."""
    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "drop-col.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            with engine.begin() as connection:
                config = _config_for(connection)
                command.upgrade(config, _PREV_REV)
                cols_before = {c["name"] for c in inspect(connection).get_columns("ScenarioResultEntries")}
                assert "error_attack_result_ids_json" in cols_before

                command.upgrade(config, _SCENARIO_LINKAGE_REV)
                cols_after = {c["name"] for c in inspect(connection).get_columns("ScenarioResultEntries")}
                assert "error_attack_result_ids_json" not in cols_after
        finally:
            engine.dispose()


def test_migration_downgrade_restores_dropped_column():
    """Downgrading from the linkage revision re-adds error_attack_result_ids_json
    and removes the new AttackResultEntries columns."""
    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "downgrade-linkage.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            with engine.begin() as connection:
                config = _config_for(connection)
                command.upgrade(config, _SCENARIO_LINKAGE_REV)

                attack_cols_up = {c["name"] for c in inspect(connection).get_columns("AttackResultEntries")}
                assert "attribution_parent_id" in attack_cols_up
                assert "attribution_data" in attack_cols_up

                command.downgrade(config, _PREV_REV)

                attack_cols_down = {c["name"] for c in inspect(connection).get_columns("AttackResultEntries")}
                assert "attribution_parent_id" not in attack_cols_down
                assert "attribution_data" not in attack_cols_down

                scenario_cols = {c["name"] for c in inspect(connection).get_columns("ScenarioResultEntries")}
                assert "error_attack_result_ids_json" in scenario_cols
        finally:
            engine.dispose()


def test_check_schema_migrations_calls_alembic_check():
    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "check-test.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            # First apply migrations so schema matches models
            run_schema_migrations(engine=engine)
            # Now check should succeed (no diffs)
            check_schema_migrations(engine=engine)
        finally:
            engine.dispose()


def test_generate_schema_migration_force_creates_revision():
    from unittest.mock import patch

    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "gen-force-test.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            run_schema_migrations(engine=engine)
            with patch("pyrit.memory.migration.command.revision") as mock_revision:
                generate_schema_migration(engine=engine, message="force empty", force=True)
                mock_revision.assert_called_once()
        finally:
            engine.dispose()


def test_generate_schema_migration_no_changes_raises():
    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "gen-nochange-test.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            run_schema_migrations(engine=engine)
            with pytest.raises(RuntimeError, match="No schema changes detected"):
                generate_schema_migration(engine=engine, message="should fail")
        finally:
            engine.dispose()


def test_generate_schema_migration_with_diffs_creates_revision():
    from unittest.mock import patch

    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "gen-diffs-test.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            run_schema_migrations(engine=engine)
            exc = AutogenerateDiffsDetected.__new__(AutogenerateDiffsDetected)
            with (
                patch("pyrit.memory.migration.command.check", side_effect=exc),
                patch("pyrit.memory.migration.command.revision") as mock_revision,
            ):
                generate_schema_migration(engine=engine, message="with diffs")
                mock_revision.assert_called_once()
        finally:
            engine.dispose()


def test_check_schema_migrations_silent_suppresses_output(capsys):
    """check_schema_migrations with silent=True must not print the Alembic message."""
    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "check-silent-test.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            run_schema_migrations(engine=engine, silent=True)
            capsys.readouterr()  # discard any output from setup

            check_schema_migrations(engine=engine, silent=True)

            captured = capsys.readouterr()
            assert captured.out == ""
        finally:
            engine.dispose()


def test_check_schema_migrations_not_silent_prints_output(capsys):
    """check_schema_migrations without silent prints the Alembic message tagged as Alembic output."""
    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "check-loud-test.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            run_schema_migrations(engine=engine, silent=True)
            capsys.readouterr()  # discard any output from setup

            check_schema_migrations(engine=engine, silent=False)

            captured = capsys.readouterr()
            assert f"{ALEMBIC_OUTPUT_PREFIX}No new upgrade operations detected." in captured.out
        finally:
            engine.dispose()


# =============================================================================
# Backfill tests for the Conversations table migration (b2f4c6a8d1e3)
# =============================================================================


_CONVERSATIONS_REV = "b2f4c6a8d1e3"
_CONVERSATIONS_PREV_REV = "f1a2b3c4d5e6"

_TARGET_A = '{"name": "target-a"}'
_TARGET_B = '{"name": "target-b"}'


def _seed_pre_conversations_prompt_piece(connection, *, piece_id, conversation_id, sequence, target_identifier):
    """Insert a PromptMemoryEntry row at the pre-Conversations revision."""
    connection.execute(
        text(
            'INSERT INTO "PromptMemoryEntries" '
            "(id, role, conversation_id, sequence, timestamp, labels, prompt_metadata, "
            "prompt_target_identifier, attack_identifier, original_value_data_type, "
            "original_value, converted_value_data_type, original_prompt_id) "
            "VALUES (:id, 'user', :conv, :seq, '2026-05-20', '{}', '{}', "
            ":target, '{}', 'text', 'hello', 'text', :id)"
        ),
        {"id": piece_id, "conv": conversation_id, "seq": sequence, "target": target_identifier},
    )


def test_conversations_migration_script_metadata():
    """The Conversations migration declares the expected revision chain."""
    from pyrit.memory.alembic.versions import b2f4c6a8d1e3_add_conversations_table as mig

    assert mig.revision == _CONVERSATIONS_REV
    assert mig.down_revision == _CONVERSATIONS_PREV_REV
    assert mig.branch_labels is None
    assert mig.depends_on is None


def test_conversations_backfill_populates_targets_and_handles_conflicts(caplog):
    """Upgrading to the Conversations revision backfills one row per conversation_id:
    the target comes from PromptMemoryEntries (first non-null wins on conflict),
    attack-only conversations get a null placeholder, and the per-row identifier
    columns are dropped."""
    import logging

    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "conversations-backfill.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            with engine.begin() as connection:
                config = _config_for(connection)
                command.upgrade(config, _CONVERSATIONS_PREV_REV)

                # A conversation whose two pieces share one target.
                _seed_pre_conversations_prompt_piece(
                    connection,
                    piece_id=str(uuid.uuid4()),
                    conversation_id="conv-keep",
                    sequence=0,
                    target_identifier=_TARGET_A,
                )
                _seed_pre_conversations_prompt_piece(
                    connection,
                    piece_id=str(uuid.uuid4()),
                    conversation_id="conv-keep",
                    sequence=1,
                    target_identifier=_TARGET_A,
                )
                # A conversation with two distinct non-null targets -> first wins + warning.
                _seed_pre_conversations_prompt_piece(
                    connection,
                    piece_id=str(uuid.uuid4()),
                    conversation_id="conv-conflict",
                    sequence=0,
                    target_identifier=_TARGET_A,
                )
                _seed_pre_conversations_prompt_piece(
                    connection,
                    piece_id=str(uuid.uuid4()),
                    conversation_id="conv-conflict",
                    sequence=1,
                    target_identifier=_TARGET_B,
                )
                # A conversation referenced only by an AttackResultEntry (no prompt rows).
                _seed_post_drop_attack_result(
                    connection, attack_id=str(uuid.uuid4()), conversation_id="conv-attack-only"
                )

                with caplog.at_level(logging.WARNING):
                    command.upgrade(config, _CONVERSATIONS_REV)

                rows = connection.execute(
                    text('SELECT conversation_id, target_identifier FROM "Conversations" ORDER BY conversation_id')
                ).fetchall()
                prompt_cols = {c["name"] for c in inspect(connection).get_columns("PromptMemoryEntries")}

            targets_by_conv = {r[0]: r[1] for r in rows}

            assert set(targets_by_conv) == {"conv-keep", "conv-conflict", "conv-attack-only"}
            assert targets_by_conv["conv-keep"] == _TARGET_A
            assert targets_by_conv["conv-conflict"] == _TARGET_A  # first non-null wins
            assert targets_by_conv["conv-attack-only"] is None  # placeholder for attack-only conversation

            # The conflicting targets produced a warning.
            assert any("multiple distinct" in r.message for r in caplog.records)

            # The per-row identifier columns are gone.
            assert "prompt_target_identifier" not in prompt_cols
            assert "attack_identifier" not in prompt_cols
        finally:
            engine.dispose()


def test_conversations_migration_downgrade_restores_columns():
    """Downgrading drops the Conversations table and re-adds the per-row identifier columns."""
    with tempfile.TemporaryDirectory() as temp_dir:
        db_path = os.path.join(temp_dir, "conversations-downgrade.db")
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            with engine.begin() as connection:
                config = _config_for(connection)
                command.upgrade(config, _CONVERSATIONS_REV)

                assert "Conversations" in set(inspect(connection).get_table_names())
                cols_up = {c["name"] for c in inspect(connection).get_columns("PromptMemoryEntries")}
                assert "prompt_target_identifier" not in cols_up

                command.downgrade(config, _CONVERSATIONS_PREV_REV)

                assert "Conversations" not in set(inspect(connection).get_table_names())
                cols_down = {c["name"] for c in inspect(connection).get_columns("PromptMemoryEntries")}
                assert "prompt_target_identifier" in cols_down
                assert "attack_identifier" in cols_down
        finally:
            engine.dispose()
