# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""Provider-neutral sandbox contracts and trusted local implementation."""

from pyrit.sandbox.contracts import SandboxEnvironment, SandboxProcess, SandboxProvider, SandboxSession
from pyrit.sandbox.docker_provider import (
    DockerCliUnavailableError,
    DockerComposeConfigError,
    DockerDaemonUnavailableError,
    DockerLifecycleError,
    DockerSandboxError,
    DockerSandboxProvider,
    DockerSecurityPolicyViolationError,
    DockerServiceSelectionError,
    DockerStateSecurityError,
    register_process_exit_cleanup,
)
from pyrit.sandbox.hyperv_provider import (
    HyperVSandboxEnvironment,
    HyperVSandboxProcess,
    HyperVSandboxProvider,
    HyperVSandboxSession,
)
from pyrit.sandbox.hyperv_transport import (
    EnvironmentHyperVSecretResolver,
    HyperVCliUnavailableError,
    HyperVComposeDelegationUnsupportedError,
    HyperVGuestTransport,
    HyperVLifecycleError,
    HyperVPermissionError,
    HyperVPlatformError,
    HyperVPrerequisiteError,
    HyperVSandboxError,
    HyperVSecretResolver,
    HyperVTransportError,
    HyperVUnsupportedCapabilityError,
    OpenSSHGuestTransport,
    PowerShellCommandRunner,
    PowerShellDirectGuestTransport,
)
from pyrit.sandbox.local import LocalSandboxProvider, SandboxPathEscapeError, SandboxSetupError
from pyrit.sandbox.models import (
    DockerPullPolicy,
    DockerSandboxProviderConfig,
    DockerSecurityPolicy,
    DockerServiceBuildSpec,
    HyperVComposeDelegationConfig,
    HyperVDiskStrategy,
    HyperVEnvironmentConfig,
    HyperVGuestOS,
    HyperVGuestTransportKind,
    HyperVNetworkMode,
    HyperVReadinessConfig,
    HyperVSandboxProviderConfig,
    HyperVSecretReference,
    HyperVSecureBootMode,
    HyperVSecurityPolicy,
    LocalSandboxProviderConfig,
    SandboxArtifact,
    SandboxConnectionInfo,
    SandboxEnvironmentSpec,
    SandboxExecRequest,
    SandboxExecResult,
    SandboxLimits,
    SandboxOperationContext,
    SandboxOperationStatus,
    SandboxReadResult,
    SandboxSessionSpec,
    SandboxSetupFile,
    SandboxSetupScript,
    SandboxTaskSpec,
    SandboxWriteResult,
)
from pyrit.sandbox.registry import SandboxProviderMetadata, SandboxProviderRegistry
from pyrit.sandbox.tool_adapter import SandboxToolAdapter

__all__ = [
    "DockerCliUnavailableError",
    "DockerComposeConfigError",
    "DockerDaemonUnavailableError",
    "DockerLifecycleError",
    "DockerPullPolicy",
    "DockerSandboxError",
    "DockerSandboxProvider",
    "DockerSandboxProviderConfig",
    "DockerSecurityPolicy",
    "DockerSecurityPolicyViolationError",
    "DockerServiceBuildSpec",
    "DockerServiceSelectionError",
    "DockerStateSecurityError",
    "EnvironmentHyperVSecretResolver",
    "HyperVCliUnavailableError",
    "HyperVComposeDelegationConfig",
    "HyperVComposeDelegationUnsupportedError",
    "HyperVDiskStrategy",
    "HyperVEnvironmentConfig",
    "HyperVGuestOS",
    "HyperVGuestTransport",
    "HyperVGuestTransportKind",
    "HyperVLifecycleError",
    "HyperVNetworkMode",
    "HyperVPermissionError",
    "HyperVPlatformError",
    "HyperVPrerequisiteError",
    "HyperVReadinessConfig",
    "HyperVSandboxEnvironment",
    "HyperVSandboxError",
    "HyperVSandboxProcess",
    "HyperVSandboxProvider",
    "HyperVSandboxProviderConfig",
    "HyperVSandboxSession",
    "HyperVSecretReference",
    "HyperVSecretResolver",
    "HyperVSecurityPolicy",
    "HyperVSecureBootMode",
    "HyperVTransportError",
    "HyperVUnsupportedCapabilityError",
    "LocalSandboxProvider",
    "LocalSandboxProviderConfig",
    "SandboxArtifact",
    "SandboxConnectionInfo",
    "SandboxEnvironment",
    "SandboxEnvironmentSpec",
    "SandboxExecRequest",
    "SandboxExecResult",
    "SandboxLimits",
    "SandboxOperationContext",
    "SandboxOperationStatus",
    "SandboxPathEscapeError",
    "SandboxProcess",
    "SandboxProvider",
    "SandboxProviderMetadata",
    "SandboxProviderRegistry",
    "SandboxReadResult",
    "SandboxSession",
    "SandboxSessionSpec",
    "SandboxSetupError",
    "SandboxSetupFile",
    "SandboxSetupScript",
    "SandboxTaskSpec",
    "SandboxToolAdapter",
    "SandboxWriteResult",
    "OpenSSHGuestTransport",
    "PowerShellCommandRunner",
    "PowerShellDirectGuestTransport",
    "register_process_exit_cleanup",
]
