
# Builds the pyrit environment and runs integration tests

trigger:
  branches:
    include:
      - main

schedules:
- cron: "0 5 * * *"  # 5 AM UTC = 9 PM PST (UTC-8)
  displayName: Integration Tests Daily at 05:00 AM UTC (9:00 PM PST)
  branches:
    include:
      - main
  always: true

jobs:
- template: test-job-template.yml
  parameters:
    jobName: IntegrationTests
    jobDisplayName: "Builds the pyrit environment and runs integration tests"
    testAzureSubscription: 'integration-test-service-connection'
    newDir: integration_test_directory
    testsFolder: integration
    makeTarget: integration-test
