import { makeStyles, tokens } from '@fluentui/react-components'
import { mobileTouchTarget } from '../../../styles/touchTargets'

export const useConverterPanelStyles = makeStyles({
  resizeContainer: {
    display: 'flex',
    flexDirection: 'row',
    height: '100%',
    flexShrink: 0,
    maxWidth: 'calc(100vw - 56px)',
  },
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    flex: 1,
    minWidth: 0,
    backgroundColor: tokens.colorNeutralBackground3,
    overflow: 'hidden',
  },
  resizeHandle: {
    width: '4px',
    cursor: 'col-resize',
    backgroundColor: 'transparent',
    borderRight: `1px solid ${tokens.colorNeutralStroke1}`,
    flexShrink: 0,
    ':hover': {
      backgroundColor: tokens.colorBrandBackground2,
    },
    ':active': {
      backgroundColor: tokens.colorBrandBackground,
    },
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    minHeight: '48px',
    gap: tokens.spacingHorizontalS,
  },
  tabBar: {
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    flexShrink: 0,
  },
  headerTitle: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalXXS,
    minWidth: 0,
  },
  body: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalM,
    padding: tokens.spacingHorizontalL,
    overflowY: 'auto',
    flex: 1,
  },
  hintText: {
    color: tokens.colorNeutralForeground3,
  },
  loading: {
    display: 'flex',
    justifyContent: 'center',
    paddingTop: tokens.spacingVerticalL,
  },
  converterList: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalS,
    flex: 1,
  },
  converterPicker: {
    width: '100%',
  },
  converterPickerListbox: {
    maxHeight: 'min(40rem, 75vh)',
    overflowY: 'auto',
  },
  createOption: {
    display: 'flex',
    alignItems: 'flex-start',
    width: '100%',
    gap: tokens.spacingHorizontalS,
    whiteSpace: 'normal',
  },
  registeredOption: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minWidth: 0,
    gap: tokens.spacingVerticalXXS,
    whiteSpace: 'normal',
  },
  optionText: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    gap: tokens.spacingVerticalXXS,
  },
  optionHeader: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    minWidth: 0,
    gap: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalS}`,
  },
  optionType: {
    color: tokens.colorNeutralForeground3,
    fontFamily: tokens.fontFamilyMonospace,
  },
  converterCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalXXS,
    padding: tokens.spacingVerticalS,
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  converterCardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacingHorizontalS,
    cursor: 'grab',
    userSelect: 'none',
    ':active': {
      cursor: 'grabbing',
    },
  },
  dragHandle: {
    ...mobileTouchTarget,
    cursor: 'grab',
    flexShrink: 0,
    ':active': {
      cursor: 'grabbing',
    },
  },
  previewButton: {
    alignSelf: 'flex-start',
  },
  addConvertedButton: {
    alignSelf: 'stretch',
    marginTop: 'auto',
  },
  converterName: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  llmBadge: {
    display: 'inline-block',
    marginLeft: tokens.spacingHorizontalXS,
    padding: `0 ${tokens.spacingHorizontalXXS}`,
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorPalettePurpleBackground2,
    color: tokens.colorPalettePurpleForeground2,
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold as unknown as string,
    verticalAlign: 'middle',
  },
  optionBadges: {
    display: 'flex',
    alignItems: 'center',
    gap: '2px',
    flexShrink: 0,
  },
  touchTarget: {
    ...mobileTouchTarget,
  },
  outputBox: {
    padding: tokens.spacingVerticalS,
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground2,
    minHeight: '80px',
    overflowY: 'auto' as const,
    maxHeight: '18rem',
  },
  valueSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalXS,
  },
  valueLabel: {
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  previewPre: {
    margin: 0,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground1,
  },
  emptyPreview: {
    color: tokens.colorNeutralForeground4,
    fontStyle: 'italic',
  },
  errorBody: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    overflow: 'visible',
  },
  previewImage: {
    maxWidth: '100%',
    maxHeight: '200px',
    borderRadius: tokens.borderRadiusMedium,
    objectFit: 'contain' as const,
  },
  previewAudio: {
    width: '100%',
  },
  previewVideo: {
    maxWidth: '100%',
    maxHeight: '200px',
    borderRadius: tokens.borderRadiusMedium,
  },
  fileChip: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    backgroundColor: tokens.colorNeutralBackground4,
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  fileChipName: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: tokens.fontFamilyMonospace,
    color: tokens.colorNeutralForeground1,
  },
  fileChipOpen: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXXS,
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalS}`,
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold as unknown as string,
    textDecoration: 'none',
    flexShrink: 0,
    ':hover': {
      backgroundColor: tokens.colorBrandBackgroundHover,
      color: tokens.colorNeutralForegroundOnBrand,
    },
  },
})
